name = "DynamicNLPModels"
uuid = "18c187db-a9a9-4c13-a1b2-7cf0a4f6591a"
authors = ["David Cole <dlcole3@wisc.edu", "Sungho Shin <sshin@anl.gov>", "Francois Pacaud <fpacaud@anl.gov>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[compat]
NLPModels = "0.18"
QuadraticModels = "0.7.2"
julia = "^1.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]